spring:
  application:
    name: taco-cloud
  thymeleaf:
    cache: false
  datasource:
    generate-unique-name: false
    name: tacocloud
  sql:
    init:
      schema-locations:
      - classpath:schema.sql
      data-locations:
      - classpath:data.sql
#  data:
#    mongodb:
#      host: mongodb.tacocloud.com
#      port: 27017
#      username: tacocloud
#      password: s3cr3tp455w0rd
#      database: tacoclouddb 
#  cassandra:
#    keyspace-name: taco_cloud
#    local-datacenter: datacenter1
#    contact-points:
#    - casshost-1.tacocloud.com
#    - casshost-2.tacocloud.com
#    - casshost-3.tacocloud.com
#    port: 9043
#    username: tacocloud
#    password: s3cr3tP455w0rd